stages:
  - package
  - docker

package app:
  stage: package
  image: mcr.microsoft.com/dotnet/sdk:9.0-noble
  script:
    - dotnet publish DeploymentTest -r linux-x64 --no-self-contained -o publish
  artifacts:
    paths:
      - publish/
    expire_in: 1 week

docker build app:
  stage: docker
  image: docker:20.10.16
  needs: ["package app"]
  services:
    - name: CI_REGISTRY_IMAGE/docker:20.10.16-dind
      alias: docker
  script:
    - docker build -f dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA