stages:
  - package
  - docker

image: mcr.microsoft.com/dotnet/sdk:9.0-noble

package app:
  stage: package
  script:
    - dotnet publish DeploymentTest -r linux-x64 --no-self-contained -o publish
  artifacts:
    paths:
      - publish/
    expire_in: 1 week

docker build app:
  stage: docker
  needs: ["package app"]
  script:
    - docker build dockerfile -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA